services:
  mongo:
    image: mongo:6.0
    container_name: mern-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
  backend:
    build: ./backend
    container_name: mern-backend
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npx nodemon index.js
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    container_name: mern-frontend
    ports:
      - '3000:3000'
      - '3001:3001'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
volumes:
  mongo-data:
